/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about building Java applications here: https://docs.gradle.org/9.2.0/samples/sample_building_java_applications.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Apply the java plugin for Java language support
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "server.Server"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Custom task to run server with arguments
tasks.register<JavaExec>("runServer") {
    group = "application"
    description = "Run the server application"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "server.Server"
    args = project.findProperty("args")?.toString()?.split(" ") ?: emptyList()
}

// Custom task: server
tasks.register<JavaExec>("server") {
    group = "application"
    description = "Runs server with -Pargs=<D>"

    mainClass.set("server.Server")
    classpath = sourceSets["main"].runtimeClasspath
    standardInput = System.`in`

    val argsParam = providers.gradleProperty("args").orNull ?: "30"
    args = argsParam.split(",")
}

// Custom task: client
tasks.register<JavaExec>("client") {
    group = "application"
    description = "Runs client with menu (Sign In, Log In, Exit)"

    mainClass.set("Main")
    classpath = sourceSets["main"].runtimeClasspath
    standardInput = System.`in`
}

// Custom task: tests
tasks.register("tests") {
    group = "verification"
    description = "Run tests"

    dependsOn("test")
}

// Make 'tests' task depend on compiling
tasks.named("tests") {
    dependsOn("test")
}
