/*
 * This source file was generated by the Gradle 'init' task
 */
package com.restaurante;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
  }
}
