#ifndef SPDK_CONFIG_H
#define SPDK_CONFIG_H
#define SPDK_CONFIG_AIO_FSDEV 1
#define SPDK_CONFIG_AIO_HAVE_RW_FLAGS 1
#define SPDK_CONFIG_APPS 1
#define SPDK_CONFIG_ARCH native
#undef SPDK_CONFIG_ASAN
#undef SPDK_CONFIG_AVAHI
#undef SPDK_CONFIG_CET
#define SPDK_CONFIG_COPY_FILE_RANGE 1
#undef SPDK_CONFIG_COVERAGE
#define SPDK_CONFIG_CROSS_PREFIX 
#undef SPDK_CONFIG_CRYPTO
#undef SPDK_CONFIG_CRYPTO_MLX5
#undef SPDK_CONFIG_CUDA
#undef SPDK_CONFIG_CUSTOMOCF
#undef SPDK_CONFIG_DAOS
#define SPDK_CONFIG_DAOS_DIR 
#undef SPDK_CONFIG_DEBUG
#undef SPDK_CONFIG_DPDK_COMPRESSDEV
#define SPDK_CONFIG_DPDK_DIR /home/goncalo/Guiao8/spdk/dpdk/build
#define SPDK_CONFIG_DPDK_INC_DIR 
#define SPDK_CONFIG_DPDK_LIB_DIR 
#undef SPDK_CONFIG_DPDK_PKG_CONFIG
#undef SPDK_CONFIG_DPDK_UADK
#define SPDK_CONFIG_ENV /home/goncalo/Guiao8/spdk/lib/env_dpdk
#define SPDK_CONFIG_EXAMPLES 1
#undef SPDK_CONFIG_FC
#define SPDK_CONFIG_FC_PATH 
#undef SPDK_CONFIG_FIO_PLUGIN
#define SPDK_CONFIG_FIO_SOURCE_DIR /usr/src/fio
#define SPDK_CONFIG_FSDEV 1
#undef SPDK_CONFIG_FUZZER
#define SPDK_CONFIG_FUZZER_LIB 
#undef SPDK_CONFIG_GOLANG
#define SPDK_CONFIG_HAVE_ARC4RANDOM 1
#define SPDK_CONFIG_HAVE_EVP_MAC 1
#define SPDK_CONFIG_HAVE_EXECINFO_H 1
#define SPDK_CONFIG_HAVE_KEYUTILS 1
#undef SPDK_CONFIG_HAVE_LIBARCHIVE
#undef SPDK_CONFIG_HAVE_LIBBSD
#define SPDK_CONFIG_HAVE_LIBUUID 1
#undef SPDK_CONFIG_HAVE_LZ4
#define SPDK_CONFIG_HAVE_STRUCT_STAT_ST_ATIM 1
#undef SPDK_CONFIG_HAVE_STRUCT_STAT_ST_ATIMESPEC
#define SPDK_CONFIG_HAVE_UUID_GENERATE_SHA1 1
#undef SPDK_CONFIG_IDXD
#undef SPDK_CONFIG_IDXD_KERNEL
#undef SPDK_CONFIG_IPSEC_MB
#define SPDK_CONFIG_IPSEC_MB_DIR 
#define SPDK_CONFIG_ISAL 1
#define SPDK_CONFIG_ISAL_CRYPTO 1
#undef SPDK_CONFIG_ISCSI_INITIATOR
#define SPDK_CONFIG_LIBDIR 
#undef SPDK_CONFIG_LTO
#define SPDK_CONFIG_MAX_LCORES 128
#define SPDK_CONFIG_MAX_NUMA_NODES 1
#define SPDK_CONFIG_NVME_CUSE 1
#undef SPDK_CONFIG_OCF
#define SPDK_CONFIG_OCF_PATH 
#define SPDK_CONFIG_OPENSSL_PATH 
#undef SPDK_CONFIG_PGO_CAPTURE
#define SPDK_CONFIG_PGO_DIR 
#undef SPDK_CONFIG_PGO_USE
#define SPDK_CONFIG_PREFIX /usr/local
#undef SPDK_CONFIG_RAID5F
#undef SPDK_CONFIG_RBD
#undef SPDK_CONFIG_RDMA
#define SPDK_CONFIG_RDMA_PROV verbs
#undef SPDK_CONFIG_RDMA_SEND_WITH_INVAL
#undef SPDK_CONFIG_RDMA_SET_ACK_TIMEOUT
#undef SPDK_CONFIG_RDMA_SET_TOS
#define SPDK_CONFIG_SHARED 1
#undef SPDK_CONFIG_SMA
#define SPDK_CONFIG_TESTS 1
#undef SPDK_CONFIG_TSAN
#undef SPDK_CONFIG_UBLK
#undef SPDK_CONFIG_UBSAN
#define SPDK_CONFIG_UNIT_TESTS 1
#undef SPDK_CONFIG_URING
#define SPDK_CONFIG_URING_PATH 
#undef SPDK_CONFIG_URING_ZNS
#undef SPDK_CONFIG_USDT
#undef SPDK_CONFIG_VFIO_USER
#define SPDK_CONFIG_VFIO_USER_DIR 
#define SPDK_CONFIG_VHOST 1
#define SPDK_CONFIG_VIRTIO 1
#undef SPDK_CONFIG_VTUNE
#define SPDK_CONFIG_VTUNE_DIR 
#undef SPDK_CONFIG_WERROR
#define SPDK_CONFIG_WPDK_DIR 
#undef SPDK_CONFIG_XNVME
#endif /* SPDK_CONFIG_H */
