plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.25.0"
}

// Configuração do Spotless para Java
spotless {
    java {
        target("src/**/*.java")
        googleJavaFormat("1.17.0")
    }
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */



repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // SQLite JDBC Driver
    implementation("org.xerial:sqlite-jdbc:3.44.0.0")
    
    // Logging
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("org.slf4j:slf4j-simple:2.0.9")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.restaurante.App"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    javaLauncher.set(javaToolchains.launcherFor(java.toolchain))
}

// ============================================
// FAT JAR TASK
// ============================================

tasks.register<Jar>("fatJar") {
    group = "build"
    description = "Cria um JAR executável com todas as dependências incluídas"
    archiveFileName = "restaurante-app-1.0.0.jar"
    archiveClassifier = ""
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    manifest {
        attributes["Main-Class"] = "com.restaurante.App"
        attributes["Manifest-Version"] = "1.0"
    }
    
    // Incluir as classes compiladas
    from(sourceSets.main.get().output)
    
    // Incluir todas as dependências
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.isFile }.map { zipTree(it) }
    })
}

// ============================================
// CUSTOM TASKS - SERVER, CLIENT, TESTS
// ============================================

// Task: ./gradlew client
tasks.register<Exec>("client") {
    group = "restaurante"
    description = "Inicia o cliente normal da aplicação"
    
    dependsOn("fatJar")
    
    val jarPath = layout.buildDirectory.dir("libs").get().file("restaurante-app-1.0.0.jar").asFile.absolutePath
    commandLine("java", "-jar", jarPath, "client")
}

// Task: ./gradlew admin
tasks.register<Exec>("admin") {
    group = "restaurante"
    description = "Inicia o cliente administrador"
    
    dependsOn("fatJar")
    
    val jarPath = layout.buildDirectory.dir("libs").get().file("restaurante-app-1.0.0.jar").asFile.absolutePath
    commandLine("java", "-jar", jarPath, "admin")
}

// Task: ./gradlew server -Pargs="port,max_clients,db_shards"
tasks.register<Exec>("server") {
    group = "restaurante"
    description = "Inicia o servidor com argumentos: -Pargs=<port>,<max_clients>,<db_shards>"
    
    dependsOn("fatJar")
    
    val args = project.properties["args"]?.toString()?.split(",") 
        ?: listOf("8080", "10", "4")
    
    val jarPath = layout.buildDirectory.dir("libs").get().file("restaurante-app-1.0.0.jar").asFile.absolutePath
    val cmdArgs = mutableListOf("java", "-jar", jarPath, "server")
    cmdArgs.addAll(args.map { it.trim() })
    
    commandLine(*cmdArgs.toTypedArray())
}

// Task: ./gradlew tests -Poutput="path/to/output"
tasks.register<Exec>("tests") {
    group = "restaurante"
    description = "Executa testes com output em -Poutput=<directory>"
    
    dependsOn("fatJar")
    
    val outputDir = project.properties["output"]?.toString() ?: "./test-results"
    val jarPath = layout.buildDirectory.dir("libs").get().file("restaurante-app-1.0.0.jar").asFile.absolutePath
    
    commandLine("java", "-jar", jarPath, "tester", outputDir)
}
